import * as React from "react";
import Link from "next/link";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";

/**
 * shadcn/ui Button — canonical structure (cva + Radix Slot + `asChild`), with
 * the Danca Go variants substituted for the stock ones.
 *
 * shadcn is a copy-in system rather than a dependency, so the file lives in
 * the repo and is ours to restyle. Keeping the API identical means anything
 * generated by the shadcn CLI drops in without adaptation.
 */
const buttonVariants = cva(
  [
    "relative inline-flex items-center justify-center gap-2 whitespace-nowrap",
    "font-medium tracking-[-0.01em] rounded-full select-none",
    "transition-[transform,background-color,border-color,color,box-shadow,opacity]",
    "duration-300 ease-[var(--ease-out-expo)]",
    // A soft lift on hover, a press on click. Previously the only scale state
    // was the press — a button sat completely inert until the instant you
    // clicked it, which reads as unresponsive on a site this otherwise alive.
    // 1.015 is deliberately small: it's felt more than seen, which is the
    // difference between "expensive" and "bouncy".
    "hover:scale-[1.015] active:scale-[0.98]",
    "disabled:pointer-events-none disabled:opacity-40 disabled:hover:scale-100",
    "[&_svg]:size-4 [&_svg]:shrink-0 [&_svg]:pointer-events-none",
    // Specular sweep on hover. Clipped to the pill, travels once, and is
    // purely decorative — pointer-events-none so it never eats a click.
    "overflow-hidden isolate",
    "after:pointer-events-none after:absolute after:inset-0 after:-z-10",
    "after:translate-x-[-120%] after:transition-transform after:duration-700",
    "after:ease-[var(--ease-out-expo)] hover:after:translate-x-[120%]",
    "after:bg-[linear-gradient(100deg,transparent,rgb(255_255_255/0.22),transparent)]",
  ],
  {
    variants: {
      variant: {
        // Primary: white pill. Apple's "Buy" button energy.
        primary:
          "bg-ink text-void hover:bg-white/90 shadow-[0_1px_2px_rgb(0_0_0/0.5),0_8px_24px_-8px_rgb(255_255_255/0.25)]",
        // Accent: the one gold moment per screen.
        accent:
          "bg-accent text-void hover:bg-accent-bright shadow-[0_1px_2px_rgb(0_0_0/0.5),0_8px_28px_-8px_rgb(200_164_104/0.55)]",
        // Secondary: glass over dark, gradient hairline border. The glow is
        // a plain white bloom rather than gold — secondary buttons sit next
        // to a primary or accent CTA in every real usage, and giving it the
        // brand colour too would compete with whichever button is actually
        // meant to lead.
        secondary: cn(
          "text-ink bg-white/[0.06] hover:bg-white/[0.10]",
          "border border-hairline hover:border-hairline-strong backdrop-blur-xl",
          "hover:shadow-[0_8px_28px_-14px_rgb(255_255_255/0.22)]",
        ),
        // Ghost carries the faintest version of the same glow — present, so
        // "all buttons" is actually true, but restrained enough that a ghost
        // button (always the lowest-emphasis action on screen) never reads
        // as more important than the primary/secondary buttons beside it.
        ghost: "text-ink-muted hover:text-ink hover:bg-white/[0.06] hover:shadow-[0_6px_20px_-14px_rgb(255_255_255/0.14)]",
        link: "text-ink-muted hover:text-ink underline-offset-4 hover:underline rounded-none px-0 hover:scale-100 active:scale-100",
      },
      size: {
        sm: "h-9 px-4 text-[0.8125rem]",
        md: "h-11 px-6 text-sm",
        lg: "h-13 px-8 text-[0.9375rem]",
        icon: "size-11 px-0",
      },
    },
    defaultVariants: { variant: "primary", size: "md" },
  },
);

export type ButtonProps = React.ComponentPropsWithoutRef<"button"> &
  VariantProps<typeof buttonVariants> & {
    /** Render the child element instead of a <button>, inheriting the styles. */
    asChild?: boolean;
  };

function Button({ className, variant, size, asChild = false, ...props }: ButtonProps) {
  const Comp = asChild ? Slot : "button";

  return (
    <Comp
      data-slot="button"
      className={cn(buttonVariants({ variant, size }), className)}
      {...props}
    />
  );
}

export type ButtonLinkProps = React.ComponentPropsWithoutRef<typeof Link> &
  VariantProps<typeof buttonVariants>;

/**
 * Convenience wrapper for the common `<Button asChild><Link/></Button>` case.
 * Renders a real anchor, so navigation, middle-click and prefetch all work.
 */
function ButtonLink({ className, variant, size, ...props }: ButtonLinkProps) {
  return (
    <Button asChild variant={variant} size={size} className={className}>
      <Link {...props} />
    </Button>
  );
}

export { Button, ButtonLink, buttonVariants };
